apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: IotKafkaWindvane
  name: iot-kafka-windvane
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: iot-kafka-windvane
  template:
    metadata:
      labels:
        app.kubernetes.io/name: iot-kafka-windvane
    spec:
      containers:
        - image: intel-server-03:5000/iotkafkawindvane:latest
          name: iot-kafka-windvane
          imagePullPolicy: Always
          env:
            - name: KAFKA_TOPIC
              value: windDirection
          envFrom:
            - configMapRef:
                name: kafka-config
            - configMapRef:
                name: influx-config